#### **1. Mathematical Operations**

##### 1. Create two NumPy arrays of shape (3, 3) and perform element-wise addition, subtraction, multiplication, and division.

In [2]:
import numpy as np

a1 = np.arange(1,10).reshape(3,3)
a2 = np.arange(11,20).reshape(3,3)
print(a1)
print(" ")
print(a2)
print(" ")
print(a1+a2)
print(" ")
print(a1-a2)
print(" ")
print(a1*a2)
print(" ")
print(a2/a1)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
 
[[11 12 13]
 [14 15 16]
 [17 18 19]]
 
[[12 14 16]
 [18 20 22]
 [24 26 28]]
 
[[-10 -10 -10]
 [-10 -10 -10]
 [-10 -10 -10]]
 
[[ 11  24  39]
 [ 56  75  96]
 [119 144 171]]
 
[[11.          6.          4.33333333]
 [ 3.5         3.          2.66666667]
 [ 2.42857143  2.25        2.11111111]]


##### 2. Generate a NumPy array with random integers and apply square root, exponential, and logarithmic functions.

In [3]:
a3 = np.arange(1,11).reshape(2,5)
print(a3)
print(np.sqrt(a3))
print(np.exp(a3))
print(np.log(a3))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[1.         1.41421356 1.73205081 2.         2.23606798]
 [2.44948974 2.64575131 2.82842712 3.         3.16227766]]
[[2.71828183e+00 7.38905610e+00 2.00855369e+01 5.45981500e+01
  1.48413159e+02]
 [4.03428793e+02 1.09663316e+03 2.98095799e+03 8.10308393e+03
  2.20264658e+04]]
[[0.         0.69314718 1.09861229 1.38629436 1.60943791]
 [1.79175947 1.94591015 2.07944154 2.19722458 2.30258509]]


##### 3. Create a NumPy array and apply trigonometric operations like sin, cos, and tan.

In [4]:
print(np.sin(a3))
print(np.cos(a3))
print(np.tan(a3))

[[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
 [-0.2794155   0.6569866   0.98935825  0.41211849 -0.54402111]]
[[ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219]
 [ 0.96017029  0.75390225 -0.14550003 -0.91113026 -0.83907153]]
[[ 1.55740772 -2.18503986 -0.14254654  1.15782128 -3.38051501]
 [-0.29100619  0.87144798 -6.79971146 -0.45231566  0.64836083]]


##### 4. Normalize a NumPy array using vectorized operations (subtract mean and divide by std).

In [5]:
import numpy as np 

array = np.array([1,2,3,4,5])
mean = np.mean(array)
std = np.std(array)
n_array = (array - mean)/std
print(array)
print(n_array)

[1 2 3 4 5]
[-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


##### 5. Implement a function using NumPy that calculates the Euclidean distance between two points.

In [6]:
distance = np.linalg.norm(a1 - a2)
print(distance)

30.0


#### **2. Combining and Splitting Arrays**

##### 1. Create two 1D arrays and concatenate them horizontally and vertically.

In [7]:
a4 = np.arange(1,10)
a5 = np.arange(11,20)
print(np.concatenate((a4,a5)))
print(np.vstack((a4,a5)))

[ 1  2  3  4  5  6  7  8  9 11 12 13 14 15 16 17 18 19]
[[ 1  2  3  4  5  6  7  8  9]
 [11 12 13 14 15 16 17 18 19]]


##### 2. Stack multiple 2D arrays using vstack and hstack and then split them back using vsplit and hsplit.

In [8]:
a = np.array([[1, 2],
              [3, 4]])
b = np.array([[5, 6],
              [7, 8]])
c = np.vstack((a,b))
d = np.hstack((a,b))
print(c)
print(d)
print(np.vsplit(c,2))
print(np.hsplit(d,2))


[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]
[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]])]
[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]])]


##### 3. Create a 2D array and split it into 4 equal sub-arrays.

In [9]:
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
sub_arr = np.split(arr,2,axis=0)
sub_arr = [np.split(sub_ar , 2 , axis=1) for sub_ar in sub_arr]
sub_arr

[[array([[1, 2],
         [5, 6]]),
  array([[3, 4],
         [7, 8]])],
 [array([[ 9, 10],
         [13, 14]]),
  array([[11, 12],
         [15, 16]])]]

##### 4. Demonstrate the difference between concatenate, stack, and hstack functions using 2D arrays.

In [24]:
a = np.array([[1,2],[3,4]])
b = np.array([[4,5],[6,7]])

print("Array no 1 \n",a)
print("")
print("Array no 2 \n",b)

axis0 = np.concatenate((a,b),axis=0)
axis1 = np.concatenate((a,b),axis=1)
print(" ")
print("concatenate axis 0 \n",axis0)
print(" ")
print("concatenate axis 1 \n",axis1)

stack0 = np.stack((a,b),axis=0)
stack1 = np.stack((a,b),axis=1)

print(" ")
print("Stack axis 0 \n",stack0)
print(" ")
print("stack axis 1 \n",stack1)

hstack = np.hstack((a,b))

print("")
print("hstach \n",hstack)

Array no 1 
 [[1 2]
 [3 4]]

Array no 2 
 [[4 5]
 [6 7]]
 
concatenate axis 0 
 [[1 2]
 [3 4]
 [4 5]
 [6 7]]
 
concatenate axis 1 
 [[1 2 4 5]
 [3 4 6 7]]
 
Stack axis 0 
 [[[1 2]
  [3 4]]

 [[4 5]
  [6 7]]]
 
stack axis 1 
 [[[1 2]
  [4 5]]

 [[3 4]
  [6 7]]]

hstach 
 [[1 2 4 5]
 [3 4 6 7]]


##### 5. Create a 3D array and flatten it, then reshape it back to its original shape.

In [32]:
a = np.array([[
     [1,2,3]
    ,[4,5,6]
    ,[7,8,9]]])
print(a)
b = a.ravel()
print("\n",b)
c = b.reshape(1,3,3)
print("\n",c)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]

 [1 2 3 4 5 6 7 8 9]

 [[[1 2 3]
  [4 5 6]
  [7 8 9]]]


#### **3. Search, Sort, Aggregating/Statistical Functions**

##### 1. Create a NumPy array and find the index of the maximum and minimum elements.

In [36]:
a = np.array([[
     [1,2,3]
    ,[4,5,6]
    ,[7,8,9]]])

b = np.argmax(a)
print(b)
c = np.argmin(b)
print(c)

8
0


##### 2. Sort a 2D array along different axes and display the result.

In [ ]:
a = np.array([
     [1,2,3]
    ,[4,5,6]
    ,[7,8,9]])



##### 3. Generate a random NumPy array and find the mean, median, variance, and standard deviation.

##### 4. Use np.where to find all elements greater than a certain threshold in a given array.

##### 5. Create a NumPy array and count how many elements are positive, negative, or zero.