#### **1. Introduction to NumPy**

**Task 1**: Import the NumPy library and print its version.

In [4]:
! pip install numpy
import numpy as np

**Task 2**: Create a one-dimensional NumPy array of integers from 0 to 9 and print it.

In [5]:
a = np.array([0,1,2,3,4,5,6,7,8,9])
print(a)


[0 1 2 3 4 5 6 7 8 9]


**Task 3**: Generate a two-dimensional NumPy array with random values and print its shape and data type.

In [7]:
a1 = np.arange(16).reshape(8,2)
print(a1)

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]]


**Task 4**: Create a NumPy array with 50 evenly spaced values between 0 and 10.

In [8]:
np.linspace(0,10,50,dtype=float)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

**Task 5**: Write a program to demonstrate the difference between a Python list and a NumPy array by performing element-wise addition on both.

In [9]:
a = [i for i in range(10000000)]
b = [i for i in range(10000000,20000000)]

c = []
import time

start = time.time()
for i in range(len(a)):
  c.append(a[i] + b[i])
print(time.time()-start)

2.478475332260132


In [10]:
import time
a = np.arange(10000000)
b = np.arange(10000000,20000000)

start = time.time()
c = a + b
print(time.time()-start)

0.3684256076812744


---

#### **2. Creation of NumPy Arrays**

**Task 6**: Create a NumPy array of all zeros with a shape of (3, 4).

In [14]:
a1 = np.zeros((3,4))
print(a1)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


**Task 7**: Create a NumPy array of all ones with a shape of (2, 5) and a data type of float.

In [16]:
a1 = np.ones((2,5),dtype=float)
print(a1)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


**Task 8**: Use `arange()` to create a NumPy array containing numbers from 10 to 50 with a step of 5.

In [18]:
a1 = np.arange(10,50,5)
print(a1)

[10 15 20 25 30 35 40 45]


**Task 9**: Generate a 3x3 identity matrix using NumPy.

In [23]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

**Task 10**: Create a 4x4 array filled with random integers between 1 and 20.

In [28]:
a1 = np.random.randint(1,21,size=(4,4))
print(a1)

[[20  6  7 18]
 [19  6 18 13]
 [19  9 17  8]
 [19 17 15 12]]


---

#### **3. Indexing and Slicing of NumPy Arrays**

**Task 11**: Create a 1D NumPy array with values ranging from 1 to 15. Slice the array to extract elements from index 3 to 8.

In [30]:
a[3:9:]

array([3, 4, 5, 6, 7, 8])



```
# This is formatted as code
```

**Task 12**: Generate a 3x3 matrix with values ranging from 1 to 9. Retrieve the element at the second row and third column.

In [38]:
a3 = np.arange(1, 10).reshape(3, 3)
print(a3)
a3[1,2]

[[1 2 3]
 [4 5 6]
 [7 8 9]]


np.int64(6)

**Task 13**: Slice a 4x4 array to extract the last two rows and the last two columns.

In [42]:
a4 = np.arange(1,17).reshape(4,4)
print(a4)
a4[2::,2::]

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


array([[11, 12],
       [15, 16]])

**Task 14**: Create a 5x5 matrix of random integers between 10 and 50. Replace all elements in the first row with the value 100.

In [45]:
a5 = np.arange(1,26).reshape(5,5)
print(a5)
a5[0] = 100
print(a5)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
[[100 100 100 100 100]
 [  6   7   8   9  10]
 [ 11  12  13  14  15]
 [ 16  17  18  19  20]
 [ 21  22  23  24  25]]


**Task 15**: Create a 1D NumPy array of 10 elements. Use boolean indexing to filter out all values greater than 5.

In [48]:
a1 = np.arange(1,11)
[a1 > 5]

[array([False, False, False, False, False,  True,  True,  True,  True,
         True])]